//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        [DisplayName("Comment Id")]
        public int CommentId { get; set; }
        [DisplayName("Resto Id")]
        public int RestoId { get; set; }
        [DisplayName("User Name")]
        public string UserName { get; set; }
        [DisplayName("Title")]
        
        public string Title { get; set; }
        [DisplayName("Creation Date")]
        public System.DateTime CreateDate { get; set; }
        public string Rating { get; set; }
        [DisplayName("Review")]
        public string Review { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
