//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Restaurant
    {
        public Restaurant()
        {
            this.Comments = new HashSet<Comment>();
        }

        [DisplayName("Resto Id")]
        public int RestoId { get; set; }
        [DisplayName("Restaurant Name")]
        [Required(ErrorMessage = "required field")]
        public string RestoName { get; set; }
        [DisplayName("Street Number")]
        [Required(ErrorMessage = "required field")]
        public string StreetNumber { get; set; }
        [DisplayName("Street Name")]
        [Required(ErrorMessage = "required field")]
        public string StreetName { get; set; }
        [DisplayName("Postal Code")]
        [Required(ErrorMessage = "required field")]
        [StringLength(6, MinimumLength=5, ErrorMessage = "Must be between 5 or 6 characters")]
        [DataType(DataType.PostalCode)]
        public string PostalCode { get; set; }
        [DisplayName("Location")]
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        [DisplayName("Genre")]
        [Required(ErrorMessage = "required field")]
        public string Genre { get; set; }
        public string Price { get; set; }
        [DisplayName("Creation Date")]
        public System.DateTime CreateDate { get; set; }
        [DisplayName("Created By")]
        public string EnteredBy { get; set; }
        [DisplayName("Views")]
        public int Views { get; set; }
        [DisplayName("Last Modified")]
        public System.DateTime EditDate { get; set; }
        [DisplayName("Modified By")]
        public string EditBy { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
    }
}
