//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserDetail
    {
        public UserDetail()
        {
            this.Comments = new HashSet<Comment>();
            this.Restaurants = new HashSet<Restaurant>();
            this.Restaurants1 = new HashSet<Restaurant>();
        }
        
        [DisplayName("User Name")]
        [StringLength(15, MinimumLength = 5,ErrorMessage="Must be between 5 and 15 characters")]
        public string UserName { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "required field")]
        [StringLength(25, MinimumLength = 1, ErrorMessage = "Must enter an correct last Name or too long. Max 25 characters")]
        public string LastName { get; set; }
        [DisplayName("First Name")]
        [Required(ErrorMessage="required field")]
        [StringLength(25, MinimumLength = 1, ErrorMessage = "Must enter an correct First Name or too long. Max 25 characters")]
        public string FirstName { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "required field")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [DisplayName("City")]
        [Required(ErrorMessage = "required field")]
        [StringLength(25, MinimumLength = 1, ErrorMessage = "Must enter an correct city")]
       
        
        public string City { get; set; }
        [DisplayName("Country")]
        [Required(ErrorMessage = "required field")]
        [StringLength(25, MinimumLength = 1, ErrorMessage = "Must enter an correct city")]
        public string Country { get; set; }
        [DisplayName("Image Path")]
        public string ImgPath { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Restaurant> Restaurants { get; set; }
        public virtual ICollection<Restaurant> Restaurants1 { get; set; }
        public virtual User User { get; set; }
    }
}
