//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [DisplayName("User Name")]
        [Required(ErrorMessage = "required field")]
        [StringLength(15, MinimumLength = 5, ErrorMessage = "Must be between 5 and 15 characters")]
        public string UserName { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "required field")]
        [DataType(DataType.Password)]
        [StringLength(12, MinimumLength = 6, ErrorMessage = "Must be between 6 and 12 characters")]
        public string Password { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
